[package]
name = "rstdms"
version = "0.1.0"
authors = ["Adam Reeve <adreeve@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.4.3"
num_enum = "0.5.1"
id-arena = "2.2.1"

[dev-dependencies]
hex-literal = "0.3.1"
